# The optimizationBenchmarking.org tool suite is a Java Project
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2
  
  
# install texlive: we can use this to test LaTeX document generation
install:
  - sudo apt-get update -y
  - sudo apt-get install texlive -y
  
# custom build step
script: mvn test compile package deploy site