# The optimizationBenchmarking.org tool suite is a Java Project
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2
  
  
# install texlive: we can use this to test LaTeX document generation
install:
  - sudo apt-get -q -y -f update
  - sudo apt-get -q -y -f install texlive
  - sudo apt-get -q -y -f install r-base r-base-dev
  
# custom build step
script: mvn -C -B test compile