# The optimizationBenchmarking.org tool suite is a Java Project
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  
# Build notifications: If the build fails, send an email.
notifications:
  email:
    on_success: never
    on_failure: always